wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"

mqtt_broker: "82.156.45.208"
mqtt_username: "esp32"
mqtt_password: "YOUR_MQTT_PASSWORD"

esphome_api_key: "YOUR_ESPHOME_API_ENCRYPTION_KEY"
esphome_ota_password: "YOUR_ESPHOME_OTA_PASSWORD"
fallback_ap_password: "YOUR_FALLBACK_AP_PASSWORD"
