import type { Component } from "vue";
import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Brain,
  Building2,
  CalendarClock,
  Camera,
  ClipboardList,
  Cpu,
  Factory,
  FileText,
  Gauge,
  Hand,
  Images,
  Image,
  KeyRound,
  LayoutDashboard,
  Leaf,
  Map,
  Router,
  ScanSearch,
  ScrollText,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  TowerControl,
  UserCog,
  Users,
  Workflow,
  BookOpen,
  FerrisWheel
} from "lucide-vue-next";

export const domainIcons = {
  operations: Gauge,
  field: Factory,
  intelligence_ops: Brain,
  platform: Building2
} as const satisfies Record<string, Component>;

export const pageIcons = {
  dashboard_overview: LayoutDashboard,
  monitor_realtime: Activity,
  monitor_history: BarChart3,
  camera_timeline: Images,
  areas: Map,
  gateways: Router,
  firmware_packages: Cpu,
  firmware_jobs: ClipboardList,
  gateway_templates: Cpu,
  sensors: Cpu,
  actuators: SlidersHorizontal,
  cameras: Camera,
  capture_plans: CalendarClock,
  capture_jobs: Image,
  media_nodes: TowerControl,
  device_shadow: ScanSearch,
  manual_control: Hand,
  automation_policy: Workflow,
  control_logs: ClipboardList,
  rule_engine: ShieldAlert,
  alert_center: Bell,
  notification_logs: Bell,
  ai_diagnosis: Bot,
  ai_reports: FileText,
  crop_knowledge: Leaf,
  ai_tasks: FerrisWheel,
  tenants: Building2,
  device_credentials: KeyRound,
  settings: Settings2,
  metrics_catalog: BookOpen,
  system_health: Gauge,
  audit_logs: ScrollText,
  users: Users,
  roles: UserCog,
  permissions: ShieldCheck
} as const satisfies Record<string, Component>;
