USE `agri_iot_platform_dev`;

CREATE TABLE IF NOT EXISTS `sys_tenants` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户主键',
  `tenant_code` VARCHAR(64) NOT NULL COMMENT '租户编码',
  `tenant_name` VARCHAR(128) NOT NULL COMMENT '租户名称',
  `tenant_slug` VARCHAR(128) DEFAULT NULL COMMENT '租户标识',
  `tenant_type` VARCHAR(32) NOT NULL DEFAULT 'enterprise' COMMENT '租户类型：enterprise/trial/internal',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled/expired',
  `is_default` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否默认租户',
  `contact_name` VARCHAR(64) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(128) DEFAULT NULL COMMENT '联系邮箱',
  `expires_at` DATETIME DEFAULT NULL COMMENT '到期时间',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_tenants_tenant_code` (`tenant_code`),
  UNIQUE KEY `uk_sys_tenants_tenant_slug` (`tenant_slug`),
  KEY `idx_sys_tenants_status_default` (`status`, `is_default`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户主表';

CREATE TABLE IF NOT EXISTS `sys_users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `user_no` VARCHAR(32) NOT NULL COMMENT '用户编号',
  `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  `real_name` VARCHAR(64) NOT NULL COMMENT '姓名',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled/locked',
  `login_failed_attempts` INT NOT NULL DEFAULT 0 COMMENT '连续登录失败次数',
  `locked_until` DATETIME DEFAULT NULL COMMENT '锁定截止时间',
  `last_login_failed_at` DATETIME DEFAULT NULL COMMENT '最近登录失败时间',
  `last_login_at` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  `last_login_ip` VARCHAR(64) DEFAULT NULL COMMENT '最后登录IP',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_users_user_no` (`user_no`),
  UNIQUE KEY `uk_sys_users_username` (`username`),
  UNIQUE KEY `uk_sys_users_phone` (`phone`),
  KEY `idx_sys_users_status` (`status`),
  KEY `idx_sys_users_tenant_id` (`tenant_id`, `status`),
  CONSTRAINT `fk_sys_users_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE IF NOT EXISTS `sys_roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `role_code` VARCHAR(64) NOT NULL COMMENT '角色编码',
  `role_name` VARCHAR(64) NOT NULL COMMENT '角色名称',
  `role_level` INT NOT NULL DEFAULT 100 COMMENT '角色层级，数字越小权限越高',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '角色描述',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_roles_tenant_role_code` (`tenant_id`, `role_code`),
  KEY `idx_sys_roles_status` (`status`),
  KEY `idx_sys_roles_tenant_id` (`tenant_id`, `status`),
  CONSTRAINT `fk_sys_roles_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统角色表';

CREATE TABLE IF NOT EXISTS `sys_permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限主键',
  `permission_code` VARCHAR(128) NOT NULL COMMENT '权限编码',
  `permission_name` VARCHAR(128) NOT NULL COMMENT '权限名称',
  `module_code` VARCHAR(64) NOT NULL COMMENT '所属模块编码',
  `permission_type` VARCHAR(32) NOT NULL COMMENT '权限类型：page/button/api',
  `route_path` VARCHAR(255) DEFAULT NULL COMMENT '页面路由或API路径',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '权限描述',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_permissions_permission_code` (`permission_code`),
  KEY `idx_sys_permissions_module_code` (`module_code`, `permission_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统权限点表';

CREATE TABLE IF NOT EXISTS `sys_user_roles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关联主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_roles_user_role` (`user_id`, `role_id`),
  KEY `idx_sys_user_roles_role_id` (`role_id`),
  CONSTRAINT `fk_sys_user_roles_user_id` FOREIGN KEY (`user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_sys_user_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `sys_roles` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE IF NOT EXISTS `sys_role_permissions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关联主键',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
  `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '权限ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_permissions_role_permission` (`role_id`, `permission_id`),
  KEY `idx_sys_role_permissions_permission_id` (`permission_id`),
  CONSTRAINT `fk_sys_role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `sys_roles` (`id`),
  CONSTRAINT `fk_sys_role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `sys_permissions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色默认权限关联表';

CREATE TABLE IF NOT EXISTS `sys_user_permission_overrides` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '覆盖主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `permission_id` BIGINT UNSIGNED NOT NULL COMMENT '权限ID',
  `effect_type` VARCHAR(16) NOT NULL COMMENT '覆盖类型：grant/revoke',
  `effective_from` DATETIME DEFAULT NULL COMMENT '生效时间',
  `effective_to` DATETIME DEFAULT NULL COMMENT '失效时间',
  `is_temporary` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否临时授权',
  `approval_status` VARCHAR(32) NOT NULL DEFAULT 'approved' COMMENT '审批状态：pending/approved/rejected',
  `reason_text` VARCHAR(255) DEFAULT NULL COMMENT '授权原因',
  `approved_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '审批人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_user_permission_overrides_user_id` (`user_id`, `effect_type`),
  KEY `idx_sys_user_permission_overrides_effective_to` (`effective_to`),
  CONSTRAINT `fk_sys_user_permission_overrides_user_id` FOREIGN KEY (`user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_sys_user_permission_overrides_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `sys_permissions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户权限覆盖表';

CREATE TABLE IF NOT EXISTS `sys_data_scopes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '数据范围主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `scope_code` VARCHAR(64) NOT NULL COMMENT '数据范围编码',
  `scope_name` VARCHAR(64) NOT NULL COMMENT '数据范围名称',
  `scope_type` VARCHAR(32) NOT NULL COMMENT '范围类型：all/area/project/owner',
  `target_type` VARCHAR(32) NOT NULL DEFAULT 'area' COMMENT '目标对象类型',
  `target_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '目标对象ID',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '数据范围描述',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_data_scopes_tenant_scope_code` (`tenant_id`, `scope_code`),
  KEY `idx_sys_data_scopes_scope_type` (`scope_type`, `target_type`),
  KEY `idx_sys_data_scopes_tenant_id` (`tenant_id`, `target_type`),
  CONSTRAINT `fk_sys_data_scopes_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据范围定义表';

CREATE TABLE IF NOT EXISTS `sys_role_data_scopes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关联主键',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
  `data_scope_id` BIGINT UNSIGNED NOT NULL COMMENT '数据范围ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_data_scopes_role_scope` (`role_id`, `data_scope_id`),
  KEY `idx_sys_role_data_scopes_scope_id` (`data_scope_id`),
  CONSTRAINT `fk_sys_role_data_scopes_role_id` FOREIGN KEY (`role_id`) REFERENCES `sys_roles` (`id`),
  CONSTRAINT `fk_sys_role_data_scopes_scope_id` FOREIGN KEY (`data_scope_id`) REFERENCES `sys_data_scopes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色默认数据范围关联表';

CREATE TABLE IF NOT EXISTS `sys_user_data_scope_overrides` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '覆盖主键',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  `data_scope_id` BIGINT UNSIGNED NOT NULL COMMENT '数据范围ID',
  `effect_type` VARCHAR(16) NOT NULL COMMENT '覆盖类型：grant/revoke',
  `effective_from` DATETIME DEFAULT NULL COMMENT '生效时间',
  `effective_to` DATETIME DEFAULT NULL COMMENT '失效时间',
  `is_temporary` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否临时授权',
  `approval_status` VARCHAR(32) NOT NULL DEFAULT 'approved' COMMENT '审批状态',
  `reason_text` VARCHAR(255) DEFAULT NULL COMMENT '授权原因',
  `approved_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '审批人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_user_data_scope_overrides_user_id` (`user_id`, `effect_type`),
  KEY `idx_sys_user_data_scope_overrides_effective_to` (`effective_to`),
  CONSTRAINT `fk_sys_user_data_scope_overrides_user_id` FOREIGN KEY (`user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_sys_user_data_scope_overrides_scope_id` FOREIGN KEY (`data_scope_id`) REFERENCES `sys_data_scopes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户数据范围覆盖表';

CREATE TABLE IF NOT EXISTS `biz_areas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '区域主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `area_code` VARCHAR(64) NOT NULL COMMENT '区域编号',
  `area_name` VARCHAR(128) NOT NULL COMMENT '区域名称',
  `parent_area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '父级区域ID',
  `area_type` VARCHAR(32) NOT NULL COMMENT '区域类型：greenhouse/open_field/lab',
  `area_level` INT NOT NULL DEFAULT 1 COMMENT '区域层级',
  `area_size` DECIMAL(12,2) DEFAULT NULL COMMENT '面积',
  `crop_type` VARCHAR(64) DEFAULT NULL COMMENT '作物类型',
  `growth_stage` VARCHAR(64) DEFAULT NULL COMMENT '生长阶段',
  `crop_species_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '作物品类ID',
  `crop_variety_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '作物品种ID',
  `crop_stage_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '生长阶段ID',
  `weather_location_name` VARCHAR(128) DEFAULT NULL COMMENT '天气定位名称',
  `weather_provider_ref` VARCHAR(128) DEFAULT NULL COMMENT '天气源定位编码',
  `latitude` DECIMAL(10,6) DEFAULT NULL COMMENT '纬度',
  `longitude` DECIMAL(10,6) DEFAULT NULL COMMENT '经度',
  `owner_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '负责人用户ID',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_areas_tenant_area_code` (`tenant_id`, `area_code`),
  KEY `idx_biz_areas_parent_area_id` (`parent_area_id`),
  KEY `idx_biz_areas_owner_user_id` (`owner_user_id`),
  KEY `idx_biz_areas_crop_species_id` (`crop_species_id`),
  KEY `idx_biz_areas_crop_variety_id` (`crop_variety_id`),
  KEY `idx_biz_areas_crop_stage_id` (`crop_stage_id`),
  KEY `idx_biz_areas_tenant_id` (`tenant_id`, `status`),
  CONSTRAINT `fk_biz_areas_parent_area_id` FOREIGN KEY (`parent_area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_biz_areas_owner_user_id` FOREIGN KEY (`owner_user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_biz_areas_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='区域业务表';

CREATE TABLE IF NOT EXISTS `agri_crop_species` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作物品类主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `species_code` VARCHAR(64) NOT NULL COMMENT '作物品类编码',
  `species_name` VARCHAR(128) NOT NULL COMMENT '作物品类名称',
  `category_name` VARCHAR(128) DEFAULT NULL COMMENT '作物分类',
  `scientific_name` VARCHAR(128) DEFAULT NULL COMMENT '学名',
  `sort_order` INT NOT NULL DEFAULT 100 COMMENT '排序',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agri_crop_species_tenant_code` (`tenant_id`, `species_code`),
  KEY `idx_agri_crop_species_tenant_status` (`tenant_id`, `status`),
  CONSTRAINT `fk_agri_crop_species_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作物品类表';

CREATE TABLE IF NOT EXISTS `agri_crop_varieties` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作物品种主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `species_id` BIGINT UNSIGNED NOT NULL COMMENT '作物品类ID',
  `variety_code` VARCHAR(64) NOT NULL COMMENT '作物品种编码',
  `variety_name` VARCHAR(128) NOT NULL COMMENT '作物品种名称',
  `sort_order` INT NOT NULL DEFAULT 100 COMMENT '排序',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agri_crop_varieties_tenant_code` (`tenant_id`, `variety_code`),
  KEY `idx_agri_crop_varieties_species_id` (`species_id`),
  KEY `idx_agri_crop_varieties_tenant_status` (`tenant_id`, `status`),
  CONSTRAINT `fk_agri_crop_varieties_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_agri_crop_varieties_species_id` FOREIGN KEY (`species_id`) REFERENCES `agri_crop_species` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作物品种表';

CREATE TABLE IF NOT EXISTS `agri_crop_growth_stages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '生长阶段主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `species_id` BIGINT UNSIGNED NOT NULL COMMENT '作物品类ID',
  `stage_code` VARCHAR(64) NOT NULL COMMENT '阶段编码',
  `stage_name` VARCHAR(128) NOT NULL COMMENT '阶段名称',
  `stage_order` INT NOT NULL DEFAULT 10 COMMENT '阶段顺序',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agri_crop_growth_stages_tenant_species_code` (`tenant_id`, `species_id`, `stage_code`),
  KEY `idx_agri_crop_growth_stages_species_id` (`species_id`),
  KEY `idx_agri_crop_growth_stages_tenant_status` (`tenant_id`, `status`),
  CONSTRAINT `fk_agri_crop_growth_stages_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_agri_crop_growth_stages_species_id` FOREIGN KEY (`species_id`) REFERENCES `agri_crop_species` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作物生长阶段表';

CREATE TABLE IF NOT EXISTS `agri_crop_target_profiles` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作物目标主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `species_id` BIGINT UNSIGNED NOT NULL COMMENT '作物品类ID',
  `variety_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '作物品种ID',
  `stage_id` BIGINT UNSIGNED NOT NULL COMMENT '生长阶段ID',
  `metric_code` VARCHAR(64) NOT NULL COMMENT '指标编码',
  `target_min` DECIMAL(12,2) DEFAULT NULL COMMENT '推荐下限',
  `target_max` DECIMAL(12,2) DEFAULT NULL COMMENT '推荐上限',
  `optimal_value` DECIMAL(12,2) DEFAULT NULL COMMENT '推荐最佳值',
  `tolerance_text` VARCHAR(255) DEFAULT NULL COMMENT '容差说明',
  `advisory_text` VARCHAR(255) DEFAULT NULL COMMENT '建议说明',
  `source_name` VARCHAR(128) DEFAULT NULL COMMENT '知识来源',
  `sort_order` INT NOT NULL DEFAULT 100 COMMENT '排序',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_agri_crop_target_profiles_species_id` (`species_id`),
  KEY `idx_agri_crop_target_profiles_variety_id` (`variety_id`),
  KEY `idx_agri_crop_target_profiles_stage_id` (`stage_id`),
  KEY `idx_agri_crop_target_profiles_metric_code` (`metric_code`),
  KEY `idx_agri_crop_target_profiles_tenant_status` (`tenant_id`, `status`),
  CONSTRAINT `fk_agri_crop_target_profiles_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_agri_crop_target_profiles_species_id` FOREIGN KEY (`species_id`) REFERENCES `agri_crop_species` (`id`),
  CONSTRAINT `fk_agri_crop_target_profiles_variety_id` FOREIGN KEY (`variety_id`) REFERENCES `agri_crop_varieties` (`id`),
  CONSTRAINT `fk_agri_crop_target_profiles_stage_id` FOREIGN KEY (`stage_id`) REFERENCES `agri_crop_growth_stages` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作物目标画像表';

CREATE TABLE IF NOT EXISTS `iot_gateway_templates` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '设备模板主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `template_code` VARCHAR(64) NOT NULL COMMENT '模板编号',
  `template_name` VARCHAR(128) NOT NULL COMMENT '模板名称',
  `gateway_type` VARCHAR(32) NOT NULL DEFAULT 'esp32' COMMENT '适用网关类型',
  `config_json` JSON NOT NULL COMMENT '模板配置JSON',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '模板状态',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_gateway_templates_tenant_code` (`tenant_id`, `template_code`),
  KEY `idx_iot_gateway_templates_tenant_status` (`tenant_id`, `status`),
  CONSTRAINT `fk_iot_gateway_templates_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关设备模板表';

CREATE TABLE IF NOT EXISTS `iot_gateways` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '网关主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `gateway_code` VARCHAR(64) NOT NULL COMMENT '网关编号',
  `gateway_name` VARCHAR(128) NOT NULL COMMENT '网关名称',
  `gateway_type` VARCHAR(32) NOT NULL COMMENT '网关类型：esp32/gateway_box',
  `serial_no` VARCHAR(128) DEFAULT NULL COMMENT '序列号',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `ip_address` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `mac_address` VARCHAR(64) DEFAULT NULL COMMENT 'MAC地址',
  `firmware_version` VARCHAR(64) DEFAULT NULL COMMENT '固件版本',
  `device_template_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '设备模板ID',
  `device_config_json` JSON DEFAULT NULL COMMENT '设备配置JSON',
  `device_config_version` INT NOT NULL DEFAULT 1 COMMENT '设备配置版本',
  `device_config_sync_status` VARCHAR(32) NOT NULL DEFAULT 'not_configured' COMMENT '配置同步状态',
  `last_config_pushed_at` DATETIME DEFAULT NULL COMMENT '最近配置下发时间',
  `last_config_applied_at` DATETIME DEFAULT NULL COMMENT '最近配置生效时间',
  `device_config_message` VARCHAR(255) DEFAULT NULL COMMENT '配置状态说明',
  `online_status` VARCHAR(32) NOT NULL DEFAULT 'offline' COMMENT '在线状态：online/offline',
  `last_heartbeat_at` DATETIME DEFAULT NULL COMMENT '最近心跳时间',
  `wifi_rssi` INT DEFAULT NULL COMMENT 'WiFi信号强度',
  `power_status` VARCHAR(32) DEFAULT NULL COMMENT '电源状态',
  `runtime_mode` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '运行模式：manual/auto/maintenance',
  `sampling_status` VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT '采集状态：running/paused',
  `desired_sampling_status` VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT '期望采集状态：running/paused',
  `sampling_command_version` INT NOT NULL DEFAULT 0 COMMENT '采集控制命令版本',
  `applied_command_version` INT NOT NULL DEFAULT 0 COMMENT '设备已应用命令版本',
  `last_sampling_command_at` DATETIME DEFAULT NULL COMMENT '最近下发采集控制时间',
  `last_sampling_reported_at` DATETIME DEFAULT NULL COMMENT '最近回报采集状态时间',
  `cached_record_count` INT NOT NULL DEFAULT 0 COMMENT '当前离线缓存条数',
  `cache_capacity` INT NOT NULL DEFAULT 0 COMMENT '缓存容量上限',
  `last_backfill_at` DATETIME DEFAULT NULL COMMENT '最近补传时间',
  `last_backfill_failed_at` DATETIME DEFAULT NULL COMMENT '最近补传失败时间',
  `backfill_status` VARCHAR(32) NOT NULL DEFAULT 'idle' COMMENT '补传状态：idle/running/failed',
  `control_availability` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '控制可用性：enabled/disabled/limited',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '设备状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_gateways_tenant_gateway_code` (`tenant_id`, `gateway_code`),
  UNIQUE KEY `uk_iot_gateways_serial_no` (`serial_no`),
  KEY `idx_iot_gateways_area_id` (`area_id`),
  KEY `idx_iot_gateways_online_status` (`online_status`, `last_heartbeat_at`),
  KEY `idx_iot_gateways_tenant_id` (`tenant_id`, `status`),
  KEY `idx_iot_gateways_template_id` (`device_template_id`),
  CONSTRAINT `fk_iot_gateways_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_gateways_template_id` FOREIGN KEY (`device_template_id`) REFERENCES `iot_gateway_templates` (`id`),
  CONSTRAINT `fk_iot_gateways_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关设备表';

CREATE TABLE IF NOT EXISTS `iot_gateway_config_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '网关配置日志主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `gateway_id` BIGINT UNSIGNED NOT NULL COMMENT '网关ID',
  `template_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '设备模板ID',
  `config_version` INT NOT NULL DEFAULT 1 COMMENT '配置版本',
  `action_type` VARCHAR(32) NOT NULL COMMENT '动作类型：save_config/mark_applied',
  `sync_status` VARCHAR(32) NOT NULL DEFAULT 'pending_push' COMMENT '同步状态',
  `config_source` VARCHAR(32) NOT NULL DEFAULT 'gateway' COMMENT '配置来源：gateway/template/default',
  `operator_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  `message_text` VARCHAR(255) DEFAULT NULL COMMENT '状态说明',
  `config_snapshot_json` JSON DEFAULT NULL COMMENT '配置快照JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_iot_gateway_config_logs_gateway_id` (`gateway_id`, `created_at`),
  KEY `idx_iot_gateway_config_logs_tenant_id` (`tenant_id`, `created_at`),
  KEY `idx_iot_gateway_config_logs_operator_user_id` (`operator_user_id`, `created_at`),
  CONSTRAINT `fk_iot_gateway_config_logs_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_gateway_config_logs_template_id` FOREIGN KEY (`template_id`) REFERENCES `iot_gateway_templates` (`id`),
  CONSTRAINT `fk_iot_gateway_config_logs_operator_user_id` FOREIGN KEY (`operator_user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_iot_gateway_config_logs_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关配置日志表';

CREATE TABLE IF NOT EXISTS `iot_metric_defs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '指标定义主键',
  `metric_code` VARCHAR(64) NOT NULL COMMENT '指标编码',
  `metric_name` VARCHAR(64) NOT NULL COMMENT '指标名称',
  `category_code` VARCHAR(32) NOT NULL DEFAULT 'environment' COMMENT '指标分类：environment/soil/water/device/custom',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '默认单位',
  `value_type` VARCHAR(16) NOT NULL DEFAULT 'decimal' COMMENT '取值类型：decimal/integer/text/boolean',
  `precision_scale` INT NOT NULL DEFAULT 2 COMMENT '小数位数',
  `normal_min` DECIMAL(18,4) DEFAULT NULL COMMENT '正常最小值',
  `normal_max` DECIMAL(18,4) DEFAULT NULL COMMENT '正常最大值',
  `warn_min` DECIMAL(18,4) DEFAULT NULL COMMENT '告警最小阈值',
  `warn_max` DECIMAL(18,4) DEFAULT NULL COMMENT '告警最大阈值',
  `chart_color` VARCHAR(32) DEFAULT NULL COMMENT '图表颜色',
  `sort_order` INT NOT NULL DEFAULT 100 COMMENT '排序值',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_metric_defs_metric_code` (`metric_code`),
  KEY `idx_iot_metric_defs_enabled_sort_order` (`enabled`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='指标字典表';

CREATE TABLE IF NOT EXISTS `iot_sensors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '传感器主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `sensor_code` VARCHAR(64) NOT NULL COMMENT '传感器编号',
  `sensor_name` VARCHAR(128) NOT NULL COMMENT '传感器名称',
  `sensor_type` VARCHAR(64) NOT NULL COMMENT '传感器类型',
  `model_name` VARCHAR(64) DEFAULT NULL COMMENT '型号',
  `protocol_type` VARCHAR(32) DEFAULT NULL COMMENT '通信协议',
  `modbus_address` INT DEFAULT NULL COMMENT 'Modbus地址',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属网关ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `install_position` VARCHAR(128) DEFAULT NULL COMMENT '安装位置',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '计量单位',
  `current_value_decimal` DECIMAL(18,4) DEFAULT NULL COMMENT '当前数值',
  `sensor_status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled/fault',
  `calibration_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '校准状态：pending/calibrated/expired',
  `data_quality_score` DECIMAL(5,2) DEFAULT NULL COMMENT '数据质量评分',
  `last_collected_at` DATETIME DEFAULT NULL COMMENT '最后采集时间',
  `last_received_at` DATETIME DEFAULT NULL COMMENT '最后接收时间',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_sensors_tenant_sensor_code` (`tenant_id`, `sensor_code`),
  KEY `idx_iot_sensors_gateway_id` (`gateway_id`),
  KEY `idx_iot_sensors_area_id` (`area_id`, `sensor_type`),
  KEY `idx_iot_sensors_last_collected_at` (`last_collected_at`),
  KEY `idx_iot_sensors_tenant_id` (`tenant_id`, `sensor_type`),
  CONSTRAINT `fk_iot_sensors_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_sensors_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_sensors_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器设备表';

CREATE TABLE IF NOT EXISTS `iot_sensor_channels` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '传感器通道主键',
  `sensor_id` BIGINT UNSIGNED NOT NULL COMMENT '传感器ID',
  `channel_code` VARCHAR(64) NOT NULL COMMENT '通道编号',
  `channel_name` VARCHAR(128) NOT NULL COMMENT '通道名称',
  `metric_code` VARCHAR(64) NOT NULL COMMENT '指标编码',
  `register_address` INT DEFAULT NULL COMMENT '寄存器地址',
  `register_length` INT NOT NULL DEFAULT 1 COMMENT '寄存器长度',
  `scale_factor` DECIMAL(18,6) NOT NULL DEFAULT 1.000000 COMMENT '缩放系数',
  `offset_value` DECIMAL(18,6) NOT NULL DEFAULT 0.000000 COMMENT '偏移值',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '通道单位',
  `channel_order` INT NOT NULL DEFAULT 1 COMMENT '通道排序',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_sensor_channels_sensor_channel_code` (`sensor_id`, `channel_code`),
  KEY `idx_iot_sensor_channels_metric_code` (`metric_code`, `enabled`),
  CONSTRAINT `fk_iot_sensor_channels_sensor_id` FOREIGN KEY (`sensor_id`) REFERENCES `iot_sensors` (`id`),
  CONSTRAINT `fk_iot_sensor_channels_metric_code` FOREIGN KEY (`metric_code`) REFERENCES `iot_metric_defs` (`metric_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器指标通道表';

CREATE TABLE IF NOT EXISTS `iot_actuators` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '执行器主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `actuator_code` VARCHAR(64) NOT NULL COMMENT '执行器编号',
  `actuator_name` VARCHAR(128) NOT NULL COMMENT '执行器名称',
  `actuator_type` VARCHAR(64) NOT NULL COMMENT '执行器类型',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属网关ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `control_channel` VARCHAR(64) DEFAULT NULL COMMENT '控制通道',
  `desired_state_text` VARCHAR(64) DEFAULT NULL COMMENT '期望状态摘要',
  `reported_state_text` VARCHAR(64) DEFAULT NULL COMMENT '实际状态摘要',
  `shadow_status` VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '影子状态：sync/pending/diverged/unknown',
  `last_action_at` DATETIME DEFAULT NULL COMMENT '最近动作时间',
  `max_run_seconds` INT DEFAULT NULL COMMENT '最大运行时长秒数',
  `mutex_group` VARCHAR(64) DEFAULT NULL COMMENT '互斥组',
  `running_mode` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '运行模式：manual/auto',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled/fault',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_actuators_tenant_actuator_code` (`tenant_id`, `actuator_code`),
  KEY `idx_iot_actuators_gateway_id` (`gateway_id`),
  KEY `idx_iot_actuators_area_id` (`area_id`, `actuator_type`),
  KEY `idx_iot_actuators_tenant_id` (`tenant_id`, `actuator_type`),
  CONSTRAINT `fk_iot_actuators_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_actuators_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_actuators_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='执行器设备表';

CREATE TABLE IF NOT EXISTS `iot_device_shadow` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '影子状态主键',
  `actuator_id` BIGINT UNSIGNED NOT NULL COMMENT '执行器ID',
  `desired_state_json` JSON DEFAULT NULL COMMENT '期望状态JSON',
  `reported_state_json` JSON DEFAULT NULL COMMENT '实际状态JSON',
  `shadow_status` VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '影子状态：sync/pending/diverged/unknown',
  `desired_updated_at` DATETIME DEFAULT NULL COMMENT '期望状态更新时间',
  `reported_updated_at` DATETIME DEFAULT NULL COMMENT '实际状态更新时间',
  `last_command_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '最近指令ID',
  `last_command_result` VARCHAR(255) DEFAULT NULL COMMENT '最近指令结果',
  `drift_seconds` INT NOT NULL DEFAULT 0 COMMENT '状态偏差持续秒数',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_device_shadow_actuator_id` (`actuator_id`),
  KEY `idx_iot_device_shadow_shadow_status` (`shadow_status`, `reported_updated_at`),
  CONSTRAINT `fk_iot_device_shadow_actuator_id` FOREIGN KEY (`actuator_id`) REFERENCES `iot_actuators` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备影子状态表';

CREATE TABLE IF NOT EXISTS `iot_gateway_backfill_batches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '补传批次主键',
  `batch_no` VARCHAR(64) NOT NULL COMMENT '补传批次号',
  `gateway_id` BIGINT UNSIGNED NOT NULL COMMENT '网关ID',
  `cached_record_count_before` INT NOT NULL DEFAULT 0 COMMENT '补传前缓存条数',
  `uploaded_record_count` INT NOT NULL DEFAULT 0 COMMENT '成功补传条数',
  `failed_record_count` INT NOT NULL DEFAULT 0 COMMENT '补传失败条数',
  `oldest_pending_collected_at` DATETIME DEFAULT NULL COMMENT '最早待补传采集时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `status` VARCHAR(32) NOT NULL DEFAULT 'queued' COMMENT '状态：queued/running/success/partial_failed/failed',
  `failure_reason` VARCHAR(255) DEFAULT NULL COMMENT '失败原因',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_gateway_backfill_batches_batch_no` (`batch_no`),
  KEY `idx_iot_gateway_backfill_batches_gateway_id` (`gateway_id`, `started_at`),
  CONSTRAINT `fk_iot_gateway_backfill_batches_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网关补传批次表';

CREATE TABLE IF NOT EXISTS `iot_sensor_readings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '采集数据主键',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '网关ID',
  `sensor_id` BIGINT UNSIGNED NOT NULL COMMENT '传感器ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '区域ID',
  `metric_code` VARCHAR(64) NOT NULL COMMENT '指标编码',
  `metric_name` VARCHAR(64) NOT NULL COMMENT '指标名称',
  `metric_value` DECIMAL(18,4) NOT NULL COMMENT '指标值',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `data_source` VARCHAR(32) NOT NULL DEFAULT 'realtime' COMMENT '数据来源：realtime/backfill/manual',
  `is_backfilled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否补传',
  `collected_at` DATETIME NOT NULL COMMENT '采集时间',
  `received_at` DATETIME NOT NULL COMMENT '接收时间',
  `clock_synced` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否时钟同步',
  `time_uncertainty_ms` INT NOT NULL DEFAULT 0 COMMENT '时间不确定度毫秒',
  `time_quality` VARCHAR(16) NOT NULL DEFAULT 'high' COMMENT '时间可信度：high/medium/low',
  `delay_ms` INT NOT NULL DEFAULT 0 COMMENT '上报延迟毫秒',
  `quality_score` DECIMAL(5,2) DEFAULT NULL COMMENT '数据质量评分',
  `raw_payload_json` JSON DEFAULT NULL COMMENT '原始报文',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
  PRIMARY KEY (`id`),
  KEY `idx_iot_sensor_readings_sensor_id_collected_at` (`sensor_id`, `collected_at`),
  KEY `idx_iot_sensor_readings_area_id_collected_at` (`area_id`, `collected_at`),
  KEY `idx_iot_sensor_readings_gateway_id_received_at` (`gateway_id`, `received_at`),
  KEY `idx_iot_sensor_readings_data_source_time_quality` (`data_source`, `time_quality`, `collected_at`),
  CONSTRAINT `fk_iot_sensor_readings_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_sensor_readings_sensor_id` FOREIGN KEY (`sensor_id`) REFERENCES `iot_sensors` (`id`),
  CONSTRAINT `fk_iot_sensor_readings_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='传感器历史数据表';

CREATE TABLE IF NOT EXISTS `rule_definitions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '规则主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `rule_code` VARCHAR(64) NOT NULL COMMENT '规则编号',
  `rule_name` VARCHAR(128) NOT NULL COMMENT '规则名称',
  `rule_type` VARCHAR(32) NOT NULL COMMENT '规则类型：threshold/trend/anomaly',
  `target_type` VARCHAR(32) NOT NULL COMMENT '监测对象类型：sensor/actuator/area',
  `target_ids_json` JSON DEFAULT NULL COMMENT '监测对象ID列表',
  `builder_mode` VARCHAR(32) NOT NULL DEFAULT 'visual' COMMENT '编辑模式：visual/advanced',
  `condition_json` JSON NOT NULL COMMENT '条件定义JSON',
  `action_json` JSON NOT NULL COMMENT '动作定义JSON',
  `recovery_policy` VARCHAR(32) NOT NULL DEFAULT 'manual_close' COMMENT '恢复策略：auto_close/auto_downgrade/manual_close',
  `recovery_stable_seconds` INT NOT NULL DEFAULT 0 COMMENT '恢复稳定时长秒数',
  `cooldown_seconds` INT NOT NULL DEFAULT 0 COMMENT '冷却时长秒数',
  `daily_max_executions` INT NOT NULL DEFAULT 0 COMMENT '每日最大执行次数',
  `priority` INT NOT NULL DEFAULT 100 COMMENT '优先级',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人用户ID',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_definitions_tenant_rule_code` (`tenant_id`, `rule_code`),
  KEY `idx_rule_definitions_target_type` (`target_type`, `enabled`),
  KEY `idx_rule_definitions_priority` (`priority`, `enabled`),
  KEY `idx_rule_definitions_tenant_id` (`tenant_id`, `enabled`),
  CONSTRAINT `fk_rule_definitions_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='规则定义表';

CREATE TABLE IF NOT EXISTS `ops_alerts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '告警主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `alert_no` VARCHAR(64) NOT NULL COMMENT '告警编号',
  `rule_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联规则ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '区域ID',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '网关ID',
  `sensor_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '传感器ID',
  `actuator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '执行器ID',
  `alert_type` VARCHAR(32) NOT NULL COMMENT '告警类型',
  `severity` VARCHAR(32) NOT NULL COMMENT '告警级别：critical/high/medium/low',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/acknowledged/in_progress/on_hold/ignored/closed/reopened',
  `title` VARCHAR(255) NOT NULL COMMENT '告警标题',
  `content_text` TEXT COMMENT '告警内容',
  `current_value_decimal` DECIMAL(18,4) DEFAULT NULL COMMENT '当前值',
  `current_value_text` VARCHAR(128) DEFAULT NULL COMMENT '当前值文本',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '单位',
  `trigger_source` VARCHAR(32) NOT NULL DEFAULT 'rule' COMMENT '触发来源：rule/manual/system',
  `assigned_to` BIGINT UNSIGNED DEFAULT NULL COMMENT '指派处理人用户ID',
  `handled_remark` VARCHAR(255) DEFAULT NULL COMMENT '处理备注',
  `reopen_count` INT NOT NULL DEFAULT 0 COMMENT '重开次数',
  `triggered_at` DATETIME NOT NULL COMMENT '触发时间',
  `last_transition_at` DATETIME DEFAULT NULL COMMENT '最近流转时间',
  `closed_at` DATETIME DEFAULT NULL COMMENT '关闭时间',
  `closed_reason` VARCHAR(255) DEFAULT NULL COMMENT '关闭原因',
  `close_source` VARCHAR(32) DEFAULT NULL COMMENT '关闭来源：manual/auto_restore/system',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ops_alerts_alert_no` (`alert_no`),
  KEY `idx_ops_alerts_status_severity` (`status`, `severity`, `triggered_at`),
  KEY `idx_ops_alerts_area_id_status` (`area_id`, `status`, `triggered_at`),
  KEY `idx_ops_alerts_assigned_to` (`assigned_to`, `status`),
  KEY `idx_ops_alerts_tenant_id` (`tenant_id`, `status`, `triggered_at`),
  CONSTRAINT `fk_ops_alerts_rule_id` FOREIGN KEY (`rule_id`) REFERENCES `rule_definitions` (`id`),
  CONSTRAINT `fk_ops_alerts_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_ops_alerts_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_ops_alerts_sensor_id` FOREIGN KEY (`sensor_id`) REFERENCES `iot_sensors` (`id`),
  CONSTRAINT `fk_ops_alerts_actuator_id` FOREIGN KEY (`actuator_id`) REFERENCES `iot_actuators` (`id`),
  CONSTRAINT `fk_ops_alerts_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_ops_alerts_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警主表';

CREATE TABLE IF NOT EXISTS `ops_alert_transitions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '告警流转主键',
  `alert_id` BIGINT UNSIGNED NOT NULL COMMENT '告警ID',
  `from_status` VARCHAR(32) DEFAULT NULL COMMENT '原状态',
  `to_status` VARCHAR(32) NOT NULL COMMENT '目标状态',
  `action_type` VARCHAR(32) NOT NULL COMMENT '动作类型：assign/ack/process/hold/ignore/close/reopen',
  `actor_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人用户ID',
  `assigned_to` BIGINT UNSIGNED DEFAULT NULL COMMENT '指派对象用户ID',
  `remark_text` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_ops_alert_transitions_alert_id` (`alert_id`, `created_at`),
  KEY `idx_ops_alert_transitions_actor_user_id` (`actor_user_id`, `created_at`),
  CONSTRAINT `fk_ops_alert_transitions_alert_id` FOREIGN KEY (`alert_id`) REFERENCES `ops_alerts` (`id`),
  CONSTRAINT `fk_ops_alert_transitions_actor_user_id` FOREIGN KEY (`actor_user_id`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警流转记录表';

CREATE TABLE IF NOT EXISTS `ops_control_commands` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '控制指令主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `command_no` VARCHAR(64) NOT NULL COMMENT '指令编号',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '区域ID',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '网关ID',
  `actuator_id` BIGINT UNSIGNED NOT NULL COMMENT '执行器ID',
  `source_type` VARCHAR(32) NOT NULL COMMENT '来源：manual/auto/ai/schedule',
  `mode_type` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '控制模式：manual/auto',
  `control_type` VARCHAR(32) NOT NULL COMMENT '控制类型：on/off/stop',
  `requested_state_json` JSON DEFAULT NULL COMMENT '期望状态JSON',
  `duration_seconds` INT DEFAULT NULL COMMENT '持续时长秒数',
  `force_execute` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否强制执行',
  `reason_text` VARCHAR(255) DEFAULT NULL COMMENT '原因说明',
  `requested_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '发起人用户ID',
  `request_status` VARCHAR(32) NOT NULL DEFAULT 'queued' COMMENT '请求状态：queued/sent/acknowledged/executed/failed/cancelled/expired',
  `device_online` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '下发时设备是否在线',
  `backfill_in_progress` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '下发时是否处于补传中',
  `queued_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '进入队列时间',
  `sent_at` DATETIME DEFAULT NULL COMMENT '下发时间',
  `expired_at` DATETIME DEFAULT NULL COMMENT '过期时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ops_control_commands_command_no` (`command_no`),
  KEY `idx_ops_control_commands_actuator_id` (`actuator_id`, `queued_at`),
  KEY `idx_ops_control_commands_source_type` (`source_type`, `queued_at`),
  KEY `idx_ops_control_commands_request_status` (`request_status`, `queued_at`),
  KEY `idx_ops_control_commands_tenant_id` (`tenant_id`, `queued_at`),
  CONSTRAINT `fk_ops_control_commands_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_ops_control_commands_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_ops_control_commands_actuator_id` FOREIGN KEY (`actuator_id`) REFERENCES `iot_actuators` (`id`),
  CONSTRAINT `fk_ops_control_commands_requested_by` FOREIGN KEY (`requested_by`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_ops_control_commands_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='控制指令表';

CREATE TABLE IF NOT EXISTS `ops_control_executions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '控制执行结果主键',
  `command_id` BIGINT UNSIGNED NOT NULL COMMENT '控制指令ID',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '网关ID',
  `actuator_id` BIGINT UNSIGNED NOT NULL COMMENT '执行器ID',
  `execution_status` VARCHAR(32) NOT NULL COMMENT '执行状态：pending/acknowledged/running/success/failed/timeout',
  `desired_state_json` JSON DEFAULT NULL COMMENT '期望状态JSON',
  `reported_state_json` JSON DEFAULT NULL COMMENT '实际状态JSON',
  `shadow_status_after` VARCHAR(32) DEFAULT NULL COMMENT '执行后影子状态',
  `result_code` VARCHAR(64) DEFAULT NULL COMMENT '结果码',
  `result_message` VARCHAR(255) DEFAULT NULL COMMENT '结果信息',
  `ack_at` DATETIME DEFAULT NULL COMMENT '回执时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始执行时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '执行完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_ops_control_executions_command_id` (`command_id`, `created_at`),
  KEY `idx_ops_control_executions_actuator_id` (`actuator_id`, `created_at`),
  CONSTRAINT `fk_ops_control_executions_command_id` FOREIGN KEY (`command_id`) REFERENCES `ops_control_commands` (`id`),
  CONSTRAINT `fk_ops_control_executions_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_ops_control_executions_actuator_id` FOREIGN KEY (`actuator_id`) REFERENCES `iot_actuators` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='控制执行结果表';

CREATE TABLE IF NOT EXISTS `ops_notifications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '通知主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `notification_no` VARCHAR(64) NOT NULL COMMENT '通知编号',
  `alert_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联告警ID',
  `task_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联AI任务ID',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '通知渠道：sms/email/wechat/in_app',
  `receiver_type` VARCHAR(32) NOT NULL COMMENT '接收者类型：user/role/custom',
  `receiver_value` VARCHAR(255) NOT NULL COMMENT '接收者标识',
  `content_summary` VARCHAR(255) DEFAULT NULL COMMENT '内容摘要',
  `payload_json` JSON DEFAULT NULL COMMENT '通知载荷',
  `send_status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '发送状态：pending/sent/failed',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `response_text` VARCHAR(255) DEFAULT NULL COMMENT '返回消息',
  `sent_at` DATETIME DEFAULT NULL COMMENT '发送时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ops_notifications_notification_no` (`notification_no`),
  KEY `idx_ops_notifications_tenant_id` (`tenant_id`, `send_status`, `created_at`),
  KEY `idx_ops_notifications_send_status` (`send_status`, `created_at`),
  KEY `idx_ops_notifications_alert_id` (`alert_id`),
  CONSTRAINT `fk_ops_notifications_alert_id` FOREIGN KEY (`alert_id`) REFERENCES `ops_alerts` (`id`),
  CONSTRAINT `fk_ops_notifications_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知发送记录表';

CREATE TABLE IF NOT EXISTS `ai_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI任务主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `task_no` VARCHAR(64) NOT NULL COMMENT '任务编号',
  `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型：diagnosis/report',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT '触发方式：manual/event/schedule',
  `scope_type` VARCHAR(32) NOT NULL COMMENT '覆盖范围类型：area/device/global',
  `scope_ids_json` JSON DEFAULT NULL COMMENT '覆盖范围ID列表',
  `dedupe_key` VARCHAR(128) DEFAULT NULL COMMENT '去重键',
  `related_alert_count` INT NOT NULL DEFAULT 0 COMMENT '关联告警数',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/queued/running/success/failed/deduped/cancelled',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  `payload_json` JSON DEFAULT NULL COMMENT '任务载荷',
  `error_message` VARCHAR(255) DEFAULT NULL COMMENT '错误信息',
  `scheduled_at` DATETIME DEFAULT NULL COMMENT '计划执行时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始执行时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_tasks_task_no` (`task_no`),
  KEY `idx_ai_tasks_status` (`status`, `scheduled_at`),
  KEY `idx_ai_tasks_dedupe_key` (`dedupe_key`),
  KEY `idx_ai_tasks_task_type_trigger_type` (`task_type`, `trigger_type`, `created_at`),
  KEY `idx_ai_tasks_tenant_id` (`tenant_id`, `task_type`, `created_at`),
  CONSTRAINT `fk_ai_tasks_created_by` FOREIGN KEY (`created_by`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_ai_tasks_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI任务队列表';

CREATE TABLE IF NOT EXISTS `ai_reports` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'AI报告主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `report_no` VARCHAR(64) NOT NULL COMMENT '报告编号',
  `task_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '来源任务ID',
  `report_type` VARCHAR(32) NOT NULL COMMENT '报告类型：daily/weekly/monthly/diagnosis',
  `report_date` DATE NOT NULL COMMENT '报告日期',
  `version_no` INT NOT NULL DEFAULT 1 COMMENT '版本号',
  `scope_type` VARCHAR(32) NOT NULL COMMENT '覆盖范围类型',
  `scope_ids_json` JSON DEFAULT NULL COMMENT '覆盖范围ID列表',
  `status` VARCHAR(32) NOT NULL DEFAULT 'generated' COMMENT '生成状态：generated/failed/cancelled',
  `metrics_json` JSON DEFAULT NULL COMMENT '指标摘要',
  `summary_text` TEXT COMMENT 'AI总结',
  `content_markdown` LONGTEXT COMMENT '完整Markdown内容',
  `is_current_version` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否当前版本',
  `trigger_type` VARCHAR(32) NOT NULL COMMENT '触发方式',
  `generated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '生成人用户ID',
  `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_reports_report_no` (`report_no`),
  KEY `idx_ai_reports_report_type_date` (`report_type`, `report_date`),
  KEY `idx_ai_reports_scope_type` (`scope_type`, `generated_at`),
  KEY `idx_ai_reports_current_version` (`is_current_version`, `report_type`, `report_date`),
  CONSTRAINT `fk_ai_reports_task_id` FOREIGN KEY (`task_id`) REFERENCES `ai_tasks` (`id`),
  KEY `idx_ai_reports_tenant_id` (`tenant_id`, `report_type`, `report_date`),
  CONSTRAINT `fk_ai_reports_generated_by` FOREIGN KEY (`generated_by`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_ai_reports_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI报告表';

CREATE TABLE IF NOT EXISTS `sys_operation_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '操作日志主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `log_no` VARCHAR(64) NOT NULL COMMENT '日志编号',
  `module_code` VARCHAR(64) NOT NULL COMMENT '模块编码',
  `operation_type` VARCHAR(64) NOT NULL COMMENT '操作类型',
  `operator_user_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '操作人用户ID',
  `operator_ip` VARCHAR(64) DEFAULT NULL COMMENT '操作IP',
  `target_type` VARCHAR(64) DEFAULT NULL COMMENT '目标对象类型',
  `target_id` VARCHAR(64) DEFAULT NULL COMMENT '目标对象ID',
  `request_method` VARCHAR(16) DEFAULT NULL COMMENT '请求方法',
  `request_path` VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
  `request_params_json` JSON DEFAULT NULL COMMENT '请求参数',
  `result_status` VARCHAR(32) NOT NULL COMMENT '结果状态：success/failed',
  `result_message` VARCHAR(255) DEFAULT NULL COMMENT '结果说明',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_operation_logs_log_no` (`log_no`),
  KEY `idx_sys_operation_logs_tenant_created_at` (`tenant_id`, `created_at`),
  KEY `idx_sys_operation_logs_module_code_created_at` (`module_code`, `created_at`),
  KEY `idx_sys_operation_logs_operator_user_id` (`operator_user_id`, `created_at`),
  CONSTRAINT `fk_sys_operation_logs_operator_user_id` FOREIGN KEY (`operator_user_id`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_sys_operation_logs_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志表';

CREATE TABLE IF NOT EXISTS `sys_configs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '系统配置主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `config_group` VARCHAR(64) NOT NULL COMMENT '配置分组',
  `config_key` VARCHAR(128) NOT NULL COMMENT '配置键',
  `config_name` VARCHAR(128) NOT NULL COMMENT '配置名称',
  `config_value_json` JSON DEFAULT NULL COMMENT '配置值JSON',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '配置描述',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人用户ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_configs_tenant_group_key` (`tenant_id`, `config_group`, `config_key`),
  KEY `idx_sys_configs_tenant_id` (`tenant_id`, `config_group`),
  CONSTRAINT `fk_sys_configs_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `sys_users` (`id`),
  CONSTRAINT `fk_sys_configs_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表';

CREATE TABLE IF NOT EXISTS `sys_tenant_plans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '套餐主键',
  `plan_code` VARCHAR(64) NOT NULL COMMENT '套餐编码',
  `plan_name` VARCHAR(128) NOT NULL COMMENT '套餐名称',
  `plan_level` INT NOT NULL DEFAULT 100 COMMENT '套餐等级，值越小优先级越高',
  `billing_cycle` VARCHAR(32) NOT NULL DEFAULT 'annual' COMMENT '计费周期：trial/monthly/quarterly/annual/custom',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `description` VARCHAR(255) DEFAULT NULL COMMENT '套餐描述',
  `features_json` JSON DEFAULT NULL COMMENT '默认能力开关JSON',
  `limits_json` JSON DEFAULT NULL COMMENT '默认额度JSON',
  `is_builtin` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否内置套餐',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_tenant_plans_plan_code` (`plan_code`),
  KEY `idx_sys_tenant_plans_status_level` (`status`, `plan_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户套餐定义表';

CREATE TABLE IF NOT EXISTS `sys_tenant_subscriptions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '租户订阅主键',
  `tenant_id` BIGINT UNSIGNED NOT NULL COMMENT '租户ID',
  `plan_id` BIGINT UNSIGNED NOT NULL COMMENT '套餐ID',
  `subscription_status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '订阅状态：active/paused/expired/cancelled',
  `starts_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `expires_at` DATETIME DEFAULT NULL COMMENT '到期时间',
  `feature_overrides_json` JSON DEFAULT NULL COMMENT '能力覆盖配置JSON',
  `limit_overrides_json` JSON DEFAULT NULL COMMENT '额度覆盖配置JSON',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `updated_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '更新人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_tenant_subscriptions_tenant_id` (`tenant_id`),
  KEY `idx_sys_tenant_subscriptions_plan_status` (`plan_id`, `subscription_status`, `expires_at`),
  CONSTRAINT `fk_sys_tenant_subscriptions_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_sys_tenant_subscriptions_plan_id` FOREIGN KEY (`plan_id`) REFERENCES `sys_tenant_plans` (`id`),
  CONSTRAINT `fk_sys_tenant_subscriptions_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租户套餐订阅表';
