USE `agri_iot_platform_dev`;

CREATE TABLE IF NOT EXISTS `iot_media_nodes` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '媒体节点主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `node_code` VARCHAR(64) NOT NULL COMMENT '媒体节点编号',
  `node_name` VARCHAR(128) NOT NULL COMMENT '媒体节点名称',
  `node_type` VARCHAR(32) NOT NULL DEFAULT 'media_server' COMMENT '节点类型：media_server/storage_gateway/edge_gateway',
  `host_address` VARCHAR(255) NOT NULL COMMENT '主机地址',
  `api_base_url` VARCHAR(255) DEFAULT NULL COMMENT '媒体服务 API 地址',
  `rtmp_base_url` VARCHAR(255) DEFAULT NULL COMMENT 'RTMP 推流基础地址',
  `hls_base_url` VARCHAR(255) DEFAULT NULL COMMENT 'HLS 播放基础地址',
  `ftp_root_path` VARCHAR(255) DEFAULT NULL COMMENT 'FTP 根路径',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `health_status` VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '健康状态：unknown/healthy/warning/error',
  `last_heartbeat_at` DATETIME DEFAULT NULL COMMENT '最近心跳时间',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_media_nodes_tenant_node_code` (`tenant_id`, `node_code`),
  KEY `idx_iot_media_nodes_status` (`status`, `health_status`),
  KEY `idx_iot_media_nodes_tenant_id` (`tenant_id`, `status`),
  CONSTRAINT `fk_iot_media_nodes_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='媒体服务节点表';

CREATE TABLE IF NOT EXISTS `iot_cameras` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '摄像头主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `camera_code` VARCHAR(64) NOT NULL COMMENT '摄像头编号',
  `camera_name` VARCHAR(128) NOT NULL COMMENT '摄像头名称',
  `camera_type` VARCHAR(32) NOT NULL DEFAULT 'ip_camera' COMMENT '摄像头类型：ip_camera/wifi_camera/thermal_camera',
  `vendor_name` VARCHAR(64) DEFAULT NULL COMMENT '品牌',
  `model_name` VARCHAR(64) DEFAULT NULL COMMENT '型号',
  `serial_no` VARCHAR(128) DEFAULT NULL COMMENT '序列号',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属网关ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `media_node_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联媒体节点ID',
  `ip_address` VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  `mac_address` VARCHAR(64) DEFAULT NULL COMMENT 'MAC地址',
  `wifi_ssid` VARCHAR(128) DEFAULT NULL COMMENT '接入WiFi名称',
  `install_position` VARCHAR(128) DEFAULT NULL COMMENT '安装位置',
  `orientation_text` VARCHAR(64) DEFAULT NULL COMMENT '朝向说明',
  `capture_mode` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '抓图模式：manual/schedule/event',
  `stream_protocol` VARCHAR(32) NOT NULL DEFAULT 'rtsp' COMMENT '主流协议：rtsp/rtmp/http',
  `online_status` VARCHAR(32) NOT NULL DEFAULT 'offline' COMMENT '在线状态：online/offline',
  `last_online_at` DATETIME DEFAULT NULL COMMENT '最近在线时间',
  `snapshot_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用抓图',
  `record_enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用录像',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_cameras_tenant_camera_code` (`tenant_id`, `camera_code`),
  UNIQUE KEY `uk_iot_cameras_serial_no` (`serial_no`),
  KEY `idx_iot_cameras_area_id` (`area_id`, `status`),
  KEY `idx_iot_cameras_gateway_id` (`gateway_id`),
  KEY `idx_iot_cameras_media_node_id` (`media_node_id`),
  KEY `idx_iot_cameras_tenant_id` (`tenant_id`, `status`),
  CONSTRAINT `fk_iot_cameras_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_cameras_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_cameras_media_node_id` FOREIGN KEY (`media_node_id`) REFERENCES `iot_media_nodes` (`id`),
  CONSTRAINT `fk_iot_cameras_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头设备表';

CREATE TABLE IF NOT EXISTS `iot_camera_streams` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '摄像头流配置主键',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `stream_name` VARCHAR(128) NOT NULL COMMENT '流名称',
  `stream_role` VARCHAR(32) NOT NULL DEFAULT 'main' COMMENT '流角色：main/sub/snapshot/upload',
  `source_protocol` VARCHAR(32) NOT NULL DEFAULT 'rtsp' COMMENT '源协议：rtsp/rtmp/http/ftp',
  `source_url` VARCHAR(512) DEFAULT NULL COMMENT '源地址',
  `stream_username` VARCHAR(128) DEFAULT NULL COMMENT '流账号',
  `stream_password` VARCHAR(255) DEFAULT NULL COMMENT '流密码',
  `target_protocol` VARCHAR(32) DEFAULT NULL COMMENT '转出协议：rtmp/hls/webrtc/flv',
  `target_url` VARCHAR(512) DEFAULT NULL COMMENT '转出地址',
  `resolution_text` VARCHAR(64) DEFAULT NULL COMMENT '分辨率描述',
  `frame_rate` INT DEFAULT NULL COMMENT '帧率',
  `bitrate_kbps` INT DEFAULT NULL COMMENT '码率kbps',
  `is_default_stream` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否默认流',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `last_pull_at` DATETIME DEFAULT NULL COMMENT '最近拉流时间',
  `last_error_text` VARCHAR(255) DEFAULT NULL COMMENT '最近错误',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_camera_streams_camera_role` (`camera_id`, `stream_role`),
  KEY `idx_iot_camera_streams_status` (`status`, `source_protocol`),
  CONSTRAINT `fk_iot_camera_streams_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头流配置表';

CREATE TABLE IF NOT EXISTS `iot_camera_capture_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '抓图任务主键',
  `job_no` VARCHAR(64) NOT NULL COMMENT '抓图任务编号',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `trigger_type` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '触发方式：manual/schedule/event/alert',
  `trigger_source_type` VARCHAR(32) DEFAULT NULL COMMENT '触发来源类型：alert/rule/ai/user',
  `trigger_source_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '触发来源ID',
  `capture_purpose` VARCHAR(32) NOT NULL DEFAULT 'preview' COMMENT '抓图用途：preview/evidence/analysis/report',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/running/success/failed/cancelled',
  `scheduled_at` DATETIME DEFAULT NULL COMMENT '计划执行时间',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `error_message` VARCHAR(255) DEFAULT NULL COMMENT '错误信息',
  `request_params_json` JSON DEFAULT NULL COMMENT '抓图请求参数',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_camera_capture_jobs_job_no` (`job_no`),
  KEY `idx_iot_camera_capture_jobs_tenant_id` (`tenant_id`, `status`, `scheduled_at`),
  KEY `idx_iot_camera_capture_jobs_camera_status` (`camera_id`, `status`, `scheduled_at`),
  KEY `idx_iot_camera_capture_jobs_trigger_source` (`trigger_source_type`, `trigger_source_id`),
  CONSTRAINT `fk_iot_camera_capture_jobs_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_iot_camera_capture_jobs_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`),
  CONSTRAINT `fk_iot_camera_capture_jobs_created_by` FOREIGN KEY (`created_by`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头抓图任务表';

CREATE TABLE IF NOT EXISTS `iot_camera_capture_plans` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '抓图计划主键',
  `plan_no` VARCHAR(64) NOT NULL COMMENT '抓图计划编号',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `plan_name` VARCHAR(128) NOT NULL COMMENT '计划名称',
  `schedule_type` VARCHAR(32) NOT NULL DEFAULT 'interval' COMMENT '调度类型：interval/daily',
  `interval_minutes` INT DEFAULT NULL COMMENT '固定间隔分钟数',
  `daily_time` CHAR(5) DEFAULT NULL COMMENT '每日触发时间 HH:mm',
  `capture_purpose` VARCHAR(32) NOT NULL DEFAULT 'preview' COMMENT '抓图用途：preview/evidence/analysis/report',
  `status` VARCHAR(32) NOT NULL DEFAULT 'enabled' COMMENT '状态：enabled/disabled',
  `next_trigger_at` DATETIME DEFAULT NULL COMMENT '下一次触发时间',
  `last_triggered_at` DATETIME DEFAULT NULL COMMENT '最近触发时间',
  `last_success_at` DATETIME DEFAULT NULL COMMENT '最近成功时间',
  `last_failure_at` DATETIME DEFAULT NULL COMMENT '最近失败时间',
  `last_job_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '最近任务ID',
  `last_snapshot_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '最近快照ID',
  `last_error_message` VARCHAR(255) DEFAULT NULL COMMENT '最近错误信息',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_camera_capture_plans_plan_no` (`plan_no`),
  KEY `idx_iot_camera_capture_plans_tenant_id` (`tenant_id`, `status`, `next_trigger_at`),
  KEY `idx_iot_camera_capture_plans_camera_id` (`camera_id`, `status`),
  KEY `idx_iot_camera_capture_plans_schedule` (`status`, `schedule_type`, `next_trigger_at`),
  CONSTRAINT `fk_iot_camera_capture_plans_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_iot_camera_capture_plans_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`),
  CONSTRAINT `fk_iot_camera_capture_plans_created_by` FOREIGN KEY (`created_by`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头抓图计划表';

CREATE TABLE IF NOT EXISTS `iot_camera_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '抓图主键',
  `snapshot_no` VARCHAR(64) NOT NULL COMMENT '抓图编号',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `capture_job_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '关联抓图任务ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属网关ID',
  `source_type` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '来源类型：manual/schedule/event/ftp_upload',
  `captured_at` DATETIME NOT NULL COMMENT '拍摄时间',
  `received_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '接收时间',
  `storage_provider` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT '存储类型：local/minio/oss/nas',
  `bucket_name` VARCHAR(128) DEFAULT NULL COMMENT '对象存储桶',
  `object_key` VARCHAR(512) DEFAULT NULL COMMENT '对象键',
  `file_path` VARCHAR(512) DEFAULT NULL COMMENT '本地或挂载路径',
  `file_size_bytes` BIGINT UNSIGNED DEFAULT NULL COMMENT '文件大小',
  `mime_type` VARCHAR(64) DEFAULT NULL COMMENT '文件类型',
  `image_width` INT DEFAULT NULL COMMENT '图片宽度',
  `image_height` INT DEFAULT NULL COMMENT '图片高度',
  `ftp_path` VARCHAR(512) DEFAULT NULL COMMENT 'FTP 上传路径',
  `thumbnail_path` VARCHAR(512) DEFAULT NULL COMMENT '缩略图路径',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_camera_snapshots_snapshot_no` (`snapshot_no`),
  KEY `idx_iot_camera_snapshots_tenant_id` (`tenant_id`, `captured_at`),
  KEY `idx_iot_camera_snapshots_camera_time` (`camera_id`, `captured_at`),
  KEY `idx_iot_camera_snapshots_area_time` (`area_id`, `captured_at`),
  CONSTRAINT `fk_iot_camera_snapshots_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_iot_camera_snapshots_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`),
  CONSTRAINT `fk_iot_camera_snapshots_capture_job_id` FOREIGN KEY (`capture_job_id`) REFERENCES `iot_camera_capture_jobs` (`id`),
  CONSTRAINT `fk_iot_camera_snapshots_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_camera_snapshots_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头抓图结果表';

CREATE TABLE IF NOT EXISTS `iot_camera_recordings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '录像主键',
  `recording_no` VARCHAR(64) NOT NULL COMMENT '录像编号',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `area_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属区域ID',
  `gateway_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属网关ID',
  `trigger_type` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '触发方式：manual/schedule/event/alert',
  `start_time` DATETIME NOT NULL COMMENT '录像开始时间',
  `end_time` DATETIME DEFAULT NULL COMMENT '录像结束时间',
  `duration_seconds` INT DEFAULT NULL COMMENT '时长秒数',
  `storage_provider` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT '存储类型：local/minio/oss/nas',
  `bucket_name` VARCHAR(128) DEFAULT NULL COMMENT '对象存储桶',
  `object_key` VARCHAR(512) DEFAULT NULL COMMENT '对象键',
  `file_path` VARCHAR(512) DEFAULT NULL COMMENT '录像路径',
  `file_size_bytes` BIGINT UNSIGNED DEFAULT NULL COMMENT '文件大小',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/recording/completed/failed',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_camera_recordings_recording_no` (`recording_no`),
  KEY `idx_iot_camera_recordings_tenant_id` (`tenant_id`, `start_time`),
  KEY `idx_iot_camera_recordings_camera_time` (`camera_id`, `start_time`),
  CONSTRAINT `fk_iot_camera_recordings_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_iot_camera_recordings_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`),
  CONSTRAINT `fk_iot_camera_recordings_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_iot_camera_recordings_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='摄像头录像索引表';

CREATE TABLE IF NOT EXISTS `ai_image_analysis_results` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '图像分析结果主键',
  `analysis_no` VARCHAR(64) NOT NULL COMMENT '分析编号',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `snapshot_id` BIGINT UNSIGNED NOT NULL COMMENT '抓图ID',
  `camera_id` BIGINT UNSIGNED NOT NULL COMMENT '摄像头ID',
  `analysis_type` VARCHAR(32) NOT NULL DEFAULT 'scene' COMMENT '分析类型：scene/object/abnormality/growth',
  `model_provider` VARCHAR(64) DEFAULT NULL COMMENT '模型提供方',
  `model_name` VARCHAR(128) DEFAULT NULL COMMENT '模型名称',
  `risk_level` VARCHAR(32) NOT NULL DEFAULT 'low' COMMENT '风险等级：low/medium/high/critical',
  `summary_text` VARCHAR(255) DEFAULT NULL COMMENT '摘要说明',
  `result_json` JSON DEFAULT NULL COMMENT '结构化分析结果',
  `status` VARCHAR(32) NOT NULL DEFAULT 'generated' COMMENT '状态：generated/failed',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_image_analysis_results_analysis_no` (`analysis_no`),
  KEY `idx_ai_image_analysis_results_tenant_id` (`tenant_id`, `analysis_type`, `created_at`),
  KEY `idx_ai_image_analysis_results_snapshot_id` (`snapshot_id`),
  KEY `idx_ai_image_analysis_results_camera_id` (`camera_id`, `analysis_type`),
  CONSTRAINT `fk_ai_image_analysis_results_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_ai_image_analysis_results_snapshot_id` FOREIGN KEY (`snapshot_id`) REFERENCES `iot_camera_snapshots` (`id`),
  CONSTRAINT `fk_ai_image_analysis_results_camera_id` FOREIGN KEY (`camera_id`) REFERENCES `iot_cameras` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图像分析结果表';
