CREATE TABLE IF NOT EXISTS `agri_crop_recommendation_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '作物建议快照主键',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '所属租户ID',
  `snapshot_no` VARCHAR(64) NOT NULL COMMENT '快照编号',
  `area_id` BIGINT UNSIGNED NOT NULL COMMENT '区域ID',
  `recommendation_status` VARCHAR(32) NOT NULL DEFAULT 'ready' COMMENT '推荐状态',
  `report_level` VARCHAR(32) NOT NULL DEFAULT 'stable' COMMENT '报告等级：stable/data_gap/needs_action/unconfigured/no_targets',
  `report_title` VARCHAR(255) NOT NULL COMMENT '报告标题',
  `summary_text` TEXT COMMENT '报告摘要',
  `crop_text` VARCHAR(255) DEFAULT NULL COMMENT '作物文本',
  `stage_text` VARCHAR(255) DEFAULT NULL COMMENT '阶段文本',
  `weather_status` VARCHAR(64) DEFAULT NULL COMMENT '天气状态',
  `weather_summary` VARCHAR(500) DEFAULT NULL COMMENT '天气摘要',
  `weather_snapshot_json` JSON DEFAULT NULL COMMENT '天气快照',
  `metrics_snapshot_json` JSON DEFAULT NULL COMMENT '指标快照',
  `actions_snapshot_json` JSON DEFAULT NULL COMMENT '建议动作快照',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人用户ID',
  `created_by_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人名称',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agri_crop_recommendation_snapshots_no` (`snapshot_no`),
  KEY `idx_agri_crop_recommendation_snapshots_tenant_area_time` (`tenant_id`, `area_id`, `created_at`),
  KEY `idx_agri_crop_recommendation_snapshots_area_time` (`area_id`, `created_at`),
  KEY `idx_agri_crop_recommendation_snapshots_created_by` (`created_by`, `created_at`),
  CONSTRAINT `fk_agri_crop_recommendation_snapshots_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_agri_crop_recommendation_snapshots_area_id` FOREIGN KEY (`area_id`) REFERENCES `biz_areas` (`id`),
  CONSTRAINT `fk_agri_crop_recommendation_snapshots_created_by` FOREIGN KEY (`created_by`) REFERENCES `sys_users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='作物建议快照表';
