CREATE TABLE IF NOT EXISTS `iot_firmware_packages` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '租户ID',
  `package_no` VARCHAR(64) NOT NULL COMMENT '固件包编号',
  `device_type` VARCHAR(32) NOT NULL DEFAULT 'esp32' COMMENT '设备类型',
  `package_name` VARCHAR(128) NOT NULL COMMENT '固件包名称',
  `firmware_version` VARCHAR(64) NOT NULL COMMENT '固件版本',
  `hardware_version` VARCHAR(64) DEFAULT NULL COMMENT '硬件版本约束',
  `download_url` VARCHAR(512) NOT NULL COMMENT '固件下载地址',
  `file_name` VARCHAR(255) DEFAULT NULL COMMENT '固件文件名',
  `file_size_bytes` BIGINT UNSIGNED DEFAULT NULL COMMENT '文件大小字节',
  `sha256` VARCHAR(128) NOT NULL COMMENT '固件SHA256',
  `release_note` TEXT DEFAULT NULL COMMENT '发布说明',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '状态 draft/released/disabled',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_firmware_packages_no` (`package_no`),
  KEY `idx_iot_firmware_packages_tenant_status` (`tenant_id`, `status`),
  KEY `idx_iot_firmware_packages_device_version` (`device_type`, `firmware_version`),
  CONSTRAINT `fk_iot_firmware_packages_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='固件包定义表';

CREATE TABLE IF NOT EXISTS `iot_firmware_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT UNSIGNED DEFAULT NULL COMMENT '租户ID',
  `job_no` VARCHAR(64) NOT NULL COMMENT '升级任务编号',
  `gateway_id` BIGINT UNSIGNED NOT NULL COMMENT '网关ID',
  `firmware_package_id` BIGINT UNSIGNED NOT NULL COMMENT '固件包ID',
  `current_version` VARCHAR(64) DEFAULT NULL COMMENT '创建任务时设备版本',
  `target_version` VARCHAR(64) NOT NULL COMMENT '目标固件版本',
  `trigger_source` VARCHAR(32) NOT NULL DEFAULT 'manual' COMMENT '触发来源 manual/auto',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态 pending/downloading/upgrading/success/failed/cancelled',
  `progress_percent` INT NOT NULL DEFAULT 0 COMMENT '进度百分比',
  `error_message` VARCHAR(255) DEFAULT NULL COMMENT '失败说明',
  `request_json` JSON DEFAULT NULL COMMENT '请求参数快照',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `last_reported_at` DATETIME DEFAULT NULL COMMENT '设备最近回报时间',
  `reported_version` VARCHAR(64) DEFAULT NULL COMMENT '设备回报版本',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `created_by` BIGINT UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_iot_firmware_jobs_no` (`job_no`),
  KEY `idx_iot_firmware_jobs_gateway_status` (`gateway_id`, `status`),
  KEY `idx_iot_firmware_jobs_tenant_created` (`tenant_id`, `created_at`),
  CONSTRAINT `fk_iot_firmware_jobs_tenant_id` FOREIGN KEY (`tenant_id`) REFERENCES `sys_tenants` (`id`),
  CONSTRAINT `fk_iot_firmware_jobs_gateway_id` FOREIGN KEY (`gateway_id`) REFERENCES `iot_gateways` (`id`),
  CONSTRAINT `fk_iot_firmware_jobs_package_id` FOREIGN KEY (`firmware_package_id`) REFERENCES `iot_firmware_packages` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备固件升级任务表';
